backend:
  name: git-gateway
  branch: master 

media_folder: "static/uploads"
public_folder: "/uploads"

collections: 
  - name: 'articles'
    label: 'Articles'
    folder: 'articles'
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Abstract', name: 'abstract', widget: 'string'}
      - {label: 'Image', name: 'image', widget: 'image'}
      - {label: 'Author', name: 'author', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'datetime'}
      - {label: 'Content', name: 'content', widget: 'markdown'}